package com.data.itsv.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Table(name = "auth_user_role")
@Data
public class AuthUserRole implements Serializable {
    /**
     * 用户角色关联表主键
     */
    @Id
    private Integer id;

    /**
     * 用户UID
     */
    private String userId;

    /**
     * 角色ID
     */
    private Integer roleId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_user_role
     *
     * @mbg.generated Thu Dec 17 09:49:24 CST 2020
     */
    private static final long serialVersionUID = 1L;


}