package com.data.itsv.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Table(name = "auth_role_resource")
@Data
public class AuthRoleResource implements Serializable {
    /**
     * 主键ID
     */
    @Id
    private Integer id;

    /**
     * 角色ID
     */
    private Integer roleId;

    /**
     * 资源ID
     */
    private Integer resourceId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_role_resource
     *
     * @mbg.generated Thu Dec 17 09:48:41 CST 2020
     */
    private static final long serialVersionUID = 1L;


}