package com.data.itsv.model;

import java.io.Serializable;

public class SConGroupOrdAlarmRes implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 联系人分组编号
     */
    private String contactUserGroupId;

    /**
     * 告警资源编号
     */
    private String alarmResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_con_group_ord_alarm_res
     *
     * @mbg.generated Mon Dec 28 10:42:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContactUserGroupId() {
        return contactUserGroupId;
    }

    public void setContactUserGroupId(String contactUserGroupId) {
        this.contactUserGroupId = contactUserGroupId == null ? null : contactUserGroupId.trim();
    }

    public String getAlarmResId() {
        return alarmResId;
    }

    public void setAlarmResId(String alarmResId) {
        this.alarmResId = alarmResId == null ? null : alarmResId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contactUserGroupId=").append(contactUserGroupId);
        sb.append(", alarmResId=").append(alarmResId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}