package com.data.itsv.model;

import java.io.Serializable;

public class SGb2312codeheader implements Serializable {
    /**
     * 
     */
    private Integer id;

    /**
     * 前十位编码
     */
    private String codeheader;

    /**
     * 
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_gb2312codeheader
     *
     * @mbg.generated Mon Dec 28 10:44:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCodeheader() {
        return codeheader;
    }

    public void setCodeheader(String codeheader) {
        this.codeheader = codeheader == null ? null : codeheader.trim();
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", codeheader=").append(codeheader);
        sb.append(", customer=").append(customer);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}