package com.data.itsv.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
public class SLog implements Serializable {
    /**
     * 编号
     */
    private Integer id;

    /**
     * 操作类型,1:"Register"
     * 注册 2:"KeepAlive"
     * 心跳  3:"PlayOpen"
     * 打开媒体流  4:"PlayClose"
     * 关闭媒体流 5:"PlayStart"
     * 开始媒体流传输  6:"PlayStop"
     * 结束媒体流传输 7:"GetRes"
     * 获取资源  8:"GetServiceResource"
     * 获取服务资源 9:"GetDeviceResource"
     * 获取设备资源  10:"GetCamResource"
     * 获取镜头资源  11:"HisPlayOpen"
     * 请求历史视频 12:"HisPlayStart"
     * 请求历史视频传输 13:"HisLoadOpen"
     * 请求历史视频下载  14:"HisLoadStart"
     * 请求历史视频下载传输 15:"PlayQuery"
     * 历史视频查询  16:"PlayCtrl"
     * 历史视频播放控制  17:"PTZCtrl"
     * 云镜控制  18:"ReportCameraState"
     * 摄像机状态上报 19:"GetCameraState"
     * 摄像机状态获取 20:"GetStoragePlan"
     * 获取录像计划   21:"GetAlarmRes"
     * 获取报警资源  22:"ReportAlarm"
     * 报警信息上报  23:"AlarmLink"
     * 告警联动  24设备资源上下线25:配置日志
     */
    private Integer type;

    /**
     * 用户名
     */
    private String username;

    /**
     * 客户端
     */
    private String clientaddr;

    /**
     * 时间
     */
    private Date createtime;

    /**
     * 内容
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_log
     *
     * @mbg.generated Mon Dec 28 10:45:07 CST 2020
     */
    private static final long serialVersionUID = 1L;


}