package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class SMapArea implements Serializable {
    /**
     *  
     */
    private Integer objectid;

    /**
     * 
     */
    private String name;

    /**
     * 
     */
    private String code;

    /**
     * 
     */
    private Date update;

    /**
     * 
     */
    private String style;

    /**
     * 
     */
    private String aliasname;

    /**
     * 
     */
    private String shape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_map_area
     *
     * @mbg.generated Mon Dec 28 10:48:30 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getObjectid() {
        return objectid;
    }

    public void setObjectid(Integer objectid) {
        this.objectid = objectid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public Date getUpdate() {
        return update;
    }

    public void setUpdate(Date update) {
        this.update = update;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    public String getAliasname() {
        return aliasname;
    }

    public void setAliasname(String aliasname) {
        this.aliasname = aliasname == null ? null : aliasname.trim();
    }

    public String getShape() {
        return shape;
    }

    public void setShape(String shape) {
        this.shape = shape == null ? null : shape.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", objectid=").append(objectid);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", update=").append(update);
        sb.append(", style=").append(style);
        sb.append(", aliasname=").append(aliasname);
        sb.append(", shape=").append(shape);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}