package com.data.itsv.model;

import java.io.Serializable;

public class SRoleOrderAlarmRes implements Serializable {
    /**
     * 角色编号
     */
    private Integer roleId;

    /**
     * 告警资源编号
     */
    private String alarmResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_role_order_alarm_res
     *
     * @mbg.generated Mon Dec 28 10:50:12 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getRoleId() {
        return roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    public String getAlarmResId() {
        return alarmResId;
    }

    public void setAlarmResId(String alarmResId) {
        this.alarmResId = alarmResId == null ? null : alarmResId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", alarmResId=").append(alarmResId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}