package com.data.itsv.model;

import java.io.Serializable;

public class SUserOrderAlarmRes implements Serializable {
    /**
     * 用户编号
     */
    private String userCode;

    /**
     * 告警资源编号
     */
    private String alarmResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_user_order_alarm_res
     *
     * @mbg.generated Mon Dec 28 10:50:52 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    public String getAlarmResId() {
        return alarmResId;
    }

    public void setAlarmResId(String alarmResId) {
        this.alarmResId = alarmResId == null ? null : alarmResId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userCode=").append(userCode);
        sb.append(", alarmResId=").append(alarmResId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}