package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class SUserTimelimit implements Serializable {
    /**
     * 用户编号	 
     */
    private String userCode;

    /**
     * 起始日期
     */
    private Date startdate;

    /**
     * 截止日期
     */
    private Date enddate;

    /**
     * 起始时间
     */
    private Date startsecond;

    /**
     * 截止时间
     */
    private Date endsecond;

    /**
     * 星期一	
     */
    private Integer monday;

    /**
     * 星期二
     */
    private Integer tuesday;

    /**
     * 星期三
     */
    private Integer wednesday;

    /**
     * 星期四	
     */
    private Integer thursday;

    /**
     * 星期五
     */
    private Integer friday;

    /**
     * 星期六	
     */
    private Integer saturday;

    /**
     * 星期日
     */
    private Integer sunday;

    /**
     * 说明1
     */
    private String memo;

    /**
     * 编号1
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_user_timelimit
     *
     * @mbg.generated Mon Dec 28 10:51:07 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public Date getStartsecond() {
        return startsecond;
    }

    public void setStartsecond(Date startsecond) {
        this.startsecond = startsecond;
    }

    public Date getEndsecond() {
        return endsecond;
    }

    public void setEndsecond(Date endsecond) {
        this.endsecond = endsecond;
    }

    public Integer getMonday() {
        return monday;
    }

    public void setMonday(Integer monday) {
        this.monday = monday;
    }

    public Integer getTuesday() {
        return tuesday;
    }

    public void setTuesday(Integer tuesday) {
        this.tuesday = tuesday;
    }

    public Integer getWednesday() {
        return wednesday;
    }

    public void setWednesday(Integer wednesday) {
        this.wednesday = wednesday;
    }

    public Integer getThursday() {
        return thursday;
    }

    public void setThursday(Integer thursday) {
        this.thursday = thursday;
    }

    public Integer getFriday() {
        return friday;
    }

    public void setFriday(Integer friday) {
        this.friday = friday;
    }

    public Integer getSaturday() {
        return saturday;
    }

    public void setSaturday(Integer saturday) {
        this.saturday = saturday;
    }

    public Integer getSunday() {
        return sunday;
    }

    public void setSunday(Integer sunday) {
        this.sunday = sunday;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userCode=").append(userCode);
        sb.append(", startdate=").append(startdate);
        sb.append(", enddate=").append(enddate);
        sb.append(", startsecond=").append(startsecond);
        sb.append(", endsecond=").append(endsecond);
        sb.append(", monday=").append(monday);
        sb.append(", tuesday=").append(tuesday);
        sb.append(", wednesday=").append(wednesday);
        sb.append(", thursday=").append(thursday);
        sb.append(", friday=").append(friday);
        sb.append(", saturday=").append(saturday);
        sb.append(", sunday=").append(sunday);
        sb.append(", memo=").append(memo);
        sb.append(", id=").append(id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}