package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VAlarmEvidence implements Serializable {
    /**
     * 告警信息编号
     */
    private String alarmId;

    /**
     * 证据类型:1图片，2录音，3录像
     */
    private Integer evidenceType;

    /**
     * 证据URL
     */
    private String evidence;

    /**
     * 告警时间1
     */
    private Date alarmTime;

    /**
     * 证据所在服务器编号
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm_evidence
     *
     * @mbg.generated Mon Dec 28 10:51:36 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getAlarmId() {
        return alarmId;
    }

    public void setAlarmId(String alarmId) {
        this.alarmId = alarmId == null ? null : alarmId.trim();
    }

    public Integer getEvidenceType() {
        return evidenceType;
    }

    public void setEvidenceType(Integer evidenceType) {
        this.evidenceType = evidenceType;
    }

    public String getEvidence() {
        return evidence;
    }

    public void setEvidence(String evidence) {
        this.evidence = evidence == null ? null : evidence.trim();
    }

    public Date getAlarmTime() {
        return alarmTime;
    }

    public void setAlarmTime(Date alarmTime) {
        this.alarmTime = alarmTime;
    }

    public String getServiceCode() {
        return serviceCode;
    }

    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", alarmId=").append(alarmId);
        sb.append(", evidenceType=").append(evidenceType);
        sb.append(", evidence=").append(evidence);
        sb.append(", alarmTime=").append(alarmTime);
        sb.append(", serviceCode=").append(serviceCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}