package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VAlarmPro implements Serializable {
    /**
     * 报警ID
     */
    private String alarmid;

    /**
     * 处理状态
     */
    private Integer dealstatus;

    /**
     * 处理时间
     */
    private Date dealtime;

    /**
     * 处理人
     */
    private String dealer;

    /**
     * 销警时间
     */
    private Date unalarmtime;

    /**
     * 处理描述
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm_pro
     *
     * @mbg.generated Mon Dec 28 10:52:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getAlarmid() {
        return alarmid;
    }

    public void setAlarmid(String alarmid) {
        this.alarmid = alarmid == null ? null : alarmid.trim();
    }

    public Integer getDealstatus() {
        return dealstatus;
    }

    public void setDealstatus(Integer dealstatus) {
        this.dealstatus = dealstatus;
    }

    public Date getDealtime() {
        return dealtime;
    }

    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    public String getDealer() {
        return dealer;
    }

    public void setDealer(String dealer) {
        this.dealer = dealer == null ? null : dealer.trim();
    }

    public Date getUnalarmtime() {
        return unalarmtime;
    }

    public void setUnalarmtime(Date unalarmtime) {
        this.unalarmtime = unalarmtime;
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", alarmid=").append(alarmid);
        sb.append(", dealstatus=").append(dealstatus);
        sb.append(", dealtime=").append(dealtime);
        sb.append(", dealer=").append(dealer);
        sb.append(", unalarmtime=").append(unalarmtime);
        sb.append(", descs=").append(descs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}