package com.data.itsv.model;

import java.io.Serializable;

public class VAlarmSetVideolink implements Serializable {
    /**
     * 告警设置编号
     */
    private String alarmSetId;

    /**
     * 联动镜头ID
     */
    private String resid;

    /**
     * 是否联动ptz,0不，1联动
     */
    private String islinkptz;

    /**
     * 预置位
     */
    private Integer ptzpresent;

    /**
     * 是否联动录像,0不，1联动
     */
    private Integer islinkrec;

    /**
     * 录像的帧率,0不，1联动
     */
    private Integer recfps;

    /**
     * 是否联动实时视频,0不，1联动
     */
    private Integer islinkprev;

    /**
     * 是否联动抓拍,0不，1联动
     */
    private Integer islinkpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm_set_videolink
     *
     * @mbg.generated Mon Dec 28 10:52:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getAlarmSetId() {
        return alarmSetId;
    }

    public void setAlarmSetId(String alarmSetId) {
        this.alarmSetId = alarmSetId == null ? null : alarmSetId.trim();
    }

    public String getResid() {
        return resid;
    }

    public void setResid(String resid) {
        this.resid = resid == null ? null : resid.trim();
    }

    public String getIslinkptz() {
        return islinkptz;
    }

    public void setIslinkptz(String islinkptz) {
        this.islinkptz = islinkptz == null ? null : islinkptz.trim();
    }

    public Integer getPtzpresent() {
        return ptzpresent;
    }

    public void setPtzpresent(Integer ptzpresent) {
        this.ptzpresent = ptzpresent;
    }

    public Integer getIslinkrec() {
        return islinkrec;
    }

    public void setIslinkrec(Integer islinkrec) {
        this.islinkrec = islinkrec;
    }

    public Integer getRecfps() {
        return recfps;
    }

    public void setRecfps(Integer recfps) {
        this.recfps = recfps;
    }

    public Integer getIslinkprev() {
        return islinkprev;
    }

    public void setIslinkprev(Integer islinkprev) {
        this.islinkprev = islinkprev;
    }

    public Integer getIslinkpic() {
        return islinkpic;
    }

    public void setIslinkpic(Integer islinkpic) {
        this.islinkpic = islinkpic;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", alarmSetId=").append(alarmSetId);
        sb.append(", resid=").append(resid);
        sb.append(", islinkptz=").append(islinkptz);
        sb.append(", ptzpresent=").append(ptzpresent);
        sb.append(", islinkrec=").append(islinkrec);
        sb.append(", recfps=").append(recfps);
        sb.append(", islinkprev=").append(islinkprev);
        sb.append(", islinkpic=").append(islinkpic);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}