package com.data.itsv.model;

import lombok.Data;

import java.io.Serializable;
@Data
public class VAlarmSet implements Serializable {
    /**
     * 告警资源ID（20位编码，分为：镜头ID、行为分析设备通道或IO通道）
     */
    private String alarmResId;

    /**
     * 告警类型 一个告警资源的告警类型不能重复，如果告警子类型为全部时，不能再有其它子类型 
     */
    private String alarmType;

    /**
     * 描述
     */
    private String descs;

    /**
     * 告警级别,0一般告警,1次要告警,2重要告警,3严重告警
     */
    private Integer alarmLevel;

    /**
     * 是否联动地图0不联动，1联动
     */
    private Integer islinkmap;

    /**
     * 是否布防，0不不妨，1不妨
     */
    private Integer isarming;

    /**
     * 是否联动声音，0不联动，1联动
     */
    private Integer islinksoud;

    /**
     * 联动声音URL
     */
    private String sound;

    /**
     * 编号
     */
    private String alarmSetId;

    /**
     * 资源类型1视频通道，2行为分析，3IO通道
     */
    private Integer resType;

    /**
     * 通道号
     */
    private Integer channelNum;

    /**
     * 设备编号
     */
    private String fdCode;

    /**
     * 通道名称
     */
    private String channelName;

    /**
     * 经度
     */
    private Integer longitude;

    /**
     * 纬度
     */
    private Integer latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm_set
     *
     * @mbg.generated Mon Dec 28 10:52:12 CST 2020
     */
    private static final long serialVersionUID = 1L;

}