package com.data.itsv.model;

import lombok.Data;

import javax.persistence.Id;
import java.io.Serializable;
@Data
public class VAlarmIo implements Serializable {
    /**
     * id
     */
    @Id
    private Integer id;
    /**
     * 告警资源编号
     */
    private String code;

    /**
     * 名称
     */
    private String name;

    /**
     * 设备编号
     */
    private String fdCode;

    /**
     * 通道序号
     */
    private Integer indexNum;

    /**
     * 
     */
    private Integer type;

    /**
     * 经度
     */
    private Integer longitude;

    /**
     * 纬度
     */
    private Integer latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm_io
     *
     * @mbg.generated Mon Dec 28 10:51:48 CST 2020
     */
    private static final long serialVersionUID = 1L;


}