package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VAlarmSetTime implements Serializable {
    /**
     * 告警设置编号
     */
    private String alarmSetId;

    /**
     * 开始时间
     */
    private Date startTime;

    /**
     * 结束时间
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm_set_time
     *
     * @mbg.generated Mon Dec 28 10:52:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getAlarmSetId() {
        return alarmSetId;
    }

    public void setAlarmSetId(String alarmSetId) {
        this.alarmSetId = alarmSetId == null ? null : alarmSetId.trim();
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", alarmSetId=").append(alarmSetId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}