package com.data.itsv.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
@Data
public class VAlarm  extends  BaseModel implements Serializable{
    /**
     * 报警ID
     */
    private String alarmid;

    /**
     * 告警资源编号
     */
    private String alarmResCode;

    /**
     * 会话标识
     */
    private String sessionid;

    /**
     * 告警类型
     */
    private String alarmType;

    /**
     * 描述
     */
    private String description;

    /**
     * 告警级别
     */
    private Integer alarmlevel;

    /**
     * 告警源名称
     */
    private String alarmResName;

    /**
     * 告警的开始时间
     */
    private Date begintime;

    /**
     * 告警的结束时间
     */
    private Date endtime;

    /**
     * 1：告警0：正常
     */
    private Integer alarmstate;

    /**
     * 确认人
     */
    private String affirmman;

    /**
     * 确认时间1
     */
    private Date affirm;

    /**
     * 清除人
     */
    private String cleanman;

    /**
     * 清除时间
     */
    private Date cleantime;

    /**
     * 告警资源ID（20位编码，分为：镜头ID、行为分析设备通道或IO通道）
     */
    private String alarmResId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_alarm
     *
     * @mbg.generated Mon Dec 28 10:51:22 CST 2020
     */
    private static final long serialVersionUID = 1L;


}