package com.data.itsv.model;

import java.io.Serializable;

public class VAssPhoic implements Serializable {
    /**
     * 语音存储服务编号
     */
    private String assCode;

    /**
     * 语音输入通道编号
     */
    private String phonicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_ass_phoic
     *
     * @mbg.generated Mon Dec 28 10:53:36 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getAssCode() {
        return assCode;
    }

    public void setAssCode(String assCode) {
        this.assCode = assCode == null ? null : assCode.trim();
    }

    public String getPhonicCode() {
        return phonicCode;
    }

    public void setPhonicCode(String phonicCode) {
        this.phonicCode = phonicCode == null ? null : phonicCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", assCode=").append(assCode);
        sb.append(", phonicCode=").append(phonicCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}