package com.data.itsv.model;

import lombok.Data;

import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Data
public class VDirectory implements Serializable {
    /**
     * 序号
     */
    private Integer id;

    /**
     * 名称
     */
    private String name;

    /**
     * 描述
     */
    private String descs;

    /**
     * 目录编号
     */
    private String code;

    /**
     * 目录编号
     */
    private Integer parentId;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 目录等级
     */
    private Integer dirLevel;

    /**
     * 完整路径
     */
    private String fullPath;

    /**
     * 用户id
     */
    @Transient
    private String userId;
    /**
     * 用户id
     */
    @Transient
    private List<VDirectory> children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_directory
     *
     * @mbg.generated Mon Dec 28 10:53:59 CST 2020
     */
    private static final long serialVersionUID = 1L;



}