package com.data.itsv.model;

import java.io.Serializable;

public class VEmployee implements Serializable {
    /**
     * 用户编号
     */
    private String id;

    /**
     * 工号
     */
    private String code;

    /**
     * 姓名
     */
    private String name;

    /**
     * 单位编号
     */
    private String unitId;

    /**
     * 人脸照片1
     */
    private String face1;

    /**
     * 人脸照片2
     */
    private String face2;

    /**
     * 人脸照片3
     */
    private String face3;

    /**
     * 人脸照片4
     */
    private String face4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_employee
     *
     * @mbg.generated Mon Dec 28 10:54:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getUnitId() {
        return unitId;
    }

    public void setUnitId(String unitId) {
        this.unitId = unitId == null ? null : unitId.trim();
    }

    public String getFace1() {
        return face1;
    }

    public void setFace1(String face1) {
        this.face1 = face1 == null ? null : face1.trim();
    }

    public String getFace2() {
        return face2;
    }

    public void setFace2(String face2) {
        this.face2 = face2 == null ? null : face2.trim();
    }

    public String getFace3() {
        return face3;
    }

    public void setFace3(String face3) {
        this.face3 = face3 == null ? null : face3.trim();
    }

    public String getFace4() {
        return face4;
    }

    public void setFace4(String face4) {
        this.face4 = face4 == null ? null : face4.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", unitId=").append(unitId);
        sb.append(", face1=").append(face1);
        sb.append(", face2=").append(face2);
        sb.append(", face3=").append(face3);
        sb.append(", face4=").append(face4);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}