package com.data.itsv.model;

import java.io.Serializable;

public class VEvidenceFile implements Serializable {
    /**
     * ID
     */
    private String id;

    /**
     * 证据类型（1图片、2录像文件、3录音文件）
     */
    private Integer fileType;

    /**
     * 地址
     */
    private String url;

    /**
     * 引用的ID
     */
    private String referenceId;

    /**
     * 文件所在服务编号
     */
    private String serverCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_evidence_file
     *
     * @mbg.generated Mon Dec 28 10:54:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public Integer getFileType() {
        return fileType;
    }

    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    public String getReferenceId() {
        return referenceId;
    }

    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId == null ? null : referenceId.trim();
    }

    public String getServerCode() {
        return serverCode;
    }

    public void setServerCode(String serverCode) {
        this.serverCode = serverCode == null ? null : serverCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileType=").append(fileType);
        sb.append(", url=").append(url);
        sb.append(", referenceId=").append(referenceId);
        sb.append(", serverCode=").append(serverCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}