package com.data.itsv.model;


import java.io.Serializable;
import java.util.Date;

public class VFdevice extends BaseModel implements Serializable  {
    /**
     * 设备编号
     */
    private String code;

    /**
     * 设备型号编号
     */
    private Integer fdtempleteId;

    /**
     * 序号
     */
    private Integer id;

    /**
     * 设备账号
     */
    private String account;

    /**
     * 密码
     */
    private String password;

    /**
     * IP
     */
    private String ip;

    /**
     * 端口
     */
    private Integer port;

    /**
     * 创建人编号
     */
    private String createUsercode;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改人编号
     */
    private String updateUsercode;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 所在位置
     */
    private String address;

    /**
     * 所属接入服务器
     */
    private String serverCode;

    /**
     * 经度
     */
    private Integer longitude;

    /**
     * 纬度
     */
    private Integer latitude;

    /**
     * 服务上线时间
     */
    private Date onlineTime;

    /**
     * 服务下线时间
     */
    private Date offlineTime;

    /**
     * 服务上下线状态,1上线，0下线
     */
    private Integer onlineState;

    /**
     * 设备名称
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_fdevice
     *
     * @mbg.generated Mon Dec 28 10:55:39 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public Integer getFdtempleteId() {
        return fdtempleteId;
    }

    public void setFdtempleteId(Integer fdtempleteId) {
        this.fdtempleteId = fdtempleteId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String getCreateUsercode() {
        return createUsercode;
    }

    public void setCreateUsercode(String createUsercode) {
        this.createUsercode = createUsercode == null ? null : createUsercode.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUpdateUsercode() {
        return updateUsercode;
    }

    public void setUpdateUsercode(String updateUsercode) {
        this.updateUsercode = updateUsercode == null ? null : updateUsercode.trim();
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public String getServerCode() {
        return serverCode;
    }

    public void setServerCode(String serverCode) {
        this.serverCode = serverCode == null ? null : serverCode.trim();
    }

    public Integer getLongitude() {
        return longitude;
    }

    public void setLongitude(Integer longitude) {
        this.longitude = longitude;
    }

    public Integer getLatitude() {
        return latitude;
    }

    public void setLatitude(Integer latitude) {
        this.latitude = latitude;
    }

    public Date getOnlineTime() {
        return onlineTime;
    }

    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }

    public Date getOfflineTime() {
        return offlineTime;
    }

    public void setOfflineTime(Date offlineTime) {
        this.offlineTime = offlineTime;
    }

    public Integer getOnlineState() {
        return onlineState;
    }

    public void setOnlineState(Integer onlineState) {
        this.onlineState = onlineState;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", fdtempleteId=").append(fdtempleteId);
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", ip=").append(ip);
        sb.append(", port=").append(port);
        sb.append(", createUsercode=").append(createUsercode);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUsercode=").append(updateUsercode);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", address=").append(address);
        sb.append(", serverCode=").append(serverCode);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", onlineTime=").append(onlineTime);
        sb.append(", offlineTime=").append(offlineTime);
        sb.append(", onlineState=").append(onlineState);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}