package com.data.itsv.model;

import java.io.Serializable;

public class VIgroupVideo implements Serializable {
    /**
     * 分组编号
     */
    private Integer id;

    /**
     * 视频通道编号
     */
    private String videoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_igroup_video
     *
     * @mbg.generated Mon Dec 28 10:56:09 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVideoCode() {
        return videoCode;
    }

    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode == null ? null : videoCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", videoCode=").append(videoCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}