package com.data.itsv.model;

import java.io.Serializable;

public class VIlayout implements Serializable {
    /**
     * 序号
     */
    private Integer id;

    /**
     * 用户编号
     */
    private String userCode;

    /**
     * 分屏数
     */
    private Integer screenNum;

    /**
     * 名称
     */
    private String layoutName;

    /**
     * 描述
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_ilayout
     *
     * @mbg.generated Mon Dec 28 10:56:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserCode() {
        return userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    public Integer getScreenNum() {
        return screenNum;
    }

    public void setScreenNum(Integer screenNum) {
        this.screenNum = screenNum;
    }

    public String getLayoutName() {
        return layoutName;
    }

    public void setLayoutName(String layoutName) {
        this.layoutName = layoutName == null ? null : layoutName.trim();
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userCode=").append(userCode);
        sb.append(", screenNum=").append(screenNum);
        sb.append(", layoutName=").append(layoutName);
        sb.append(", descs=").append(descs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}