package com.data.itsv.model;

import java.io.Serializable;

public class VItourVideo implements Serializable {
    /**
     * 视频输入通道编号
     */
    private String videoCode;

    /**
     * 我的巡_巡视组编号
     */
    private Integer tourCode;

    /**
     * 巡逻序号 
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_itour_video
     *
     * @mbg.generated Mon Dec 28 10:58:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getVideoCode() {
        return videoCode;
    }

    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode == null ? null : videoCode.trim();
    }

    public Integer getTourCode() {
        return tourCode;
    }

    public void setTourCode(Integer tourCode) {
        this.tourCode = tourCode;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoCode=").append(videoCode);
        sb.append(", tourCode=").append(tourCode);
        sb.append(", num=").append(num);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}