package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VMaskwhitelist implements Serializable {
    /**
     * 用户编号
     */
    private String usercode;

    /**
     * 视频屏蔽计划编号
     */
    private Integer maskplanid;

    /**
     * 创建时间 
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_maskwhitelist
     *
     * @mbg.generated Mon Dec 28 10:59:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getUsercode() {
        return usercode;
    }

    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    public Integer getMaskplanid() {
        return maskplanid;
    }

    public void setMaskplanid(Integer maskplanid) {
        this.maskplanid = maskplanid;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", usercode=").append(usercode);
        sb.append(", maskplanid=").append(maskplanid);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}