package com.data.itsv.model;

import java.io.Serializable;

public class VMasterSlaveFd implements Serializable {
    /**
     * 主设备通道编号
     */
    private String masterFdChannelCode;

    /**
     * 子设备账号
     */
    private String masterFdAccount;

    /**
     * 子设备密码
     */
    private String masterFdPassword;

    /**
     * 子设备地址
     */
    private String masterFdIp;

    /**
     * 端口
     */
    private Integer masterFdProt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_master_slave_fd
     *
     * @mbg.generated Mon Dec 28 10:59:09 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getMasterFdChannelCode() {
        return masterFdChannelCode;
    }

    public void setMasterFdChannelCode(String masterFdChannelCode) {
        this.masterFdChannelCode = masterFdChannelCode == null ? null : masterFdChannelCode.trim();
    }

    public String getMasterFdAccount() {
        return masterFdAccount;
    }

    public void setMasterFdAccount(String masterFdAccount) {
        this.masterFdAccount = masterFdAccount == null ? null : masterFdAccount.trim();
    }

    public String getMasterFdPassword() {
        return masterFdPassword;
    }

    public void setMasterFdPassword(String masterFdPassword) {
        this.masterFdPassword = masterFdPassword == null ? null : masterFdPassword.trim();
    }

    public String getMasterFdIp() {
        return masterFdIp;
    }

    public void setMasterFdIp(String masterFdIp) {
        this.masterFdIp = masterFdIp == null ? null : masterFdIp.trim();
    }

    public Integer getMasterFdProt() {
        return masterFdProt;
    }

    public void setMasterFdProt(Integer masterFdProt) {
        this.masterFdProt = masterFdProt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", masterFdChannelCode=").append(masterFdChannelCode);
        sb.append(", masterFdAccount=").append(masterFdAccount);
        sb.append(", masterFdPassword=").append(masterFdPassword);
        sb.append(", masterFdIp=").append(masterFdIp);
        sb.append(", masterFdProt=").append(masterFdProt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}