package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VMaskcamera implements Serializable {
    /**
     * 创建时间 
     */
    private Date createtime;

    /**
     * 视频输入通道编号
     */
    private String videoinputCode;

    /**
     * 视频屏蔽计划编号
     */
    private Integer maskplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_maskcamera
     *
     * @mbg.generated Mon Dec 28 10:58:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getVideoinputCode() {
        return videoinputCode;
    }

    public void setVideoinputCode(String videoinputCode) {
        this.videoinputCode = videoinputCode == null ? null : videoinputCode.trim();
    }

    public Integer getMaskplanid() {
        return maskplanid;
    }

    public void setMaskplanid(Integer maskplanid) {
        this.maskplanid = maskplanid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", createtime=").append(createtime);
        sb.append(", videoinputCode=").append(videoinputCode);
        sb.append(", maskplanid=").append(maskplanid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}