package com.data.itsv.model;

import java.io.Serializable;

public class VPohic implements Serializable {
    /**
     * 编号
     */
    private String code;

    /**
     * 通道名称
     */
    private String name;

    /**
     * 备注
     */
    private String descs;

    /**
     * 音频格式：PCM    1 G711-A 2 AMR    3 G711-U 4 G726   5 G723   6 AAC    8
     */
    private Integer audioformat;

    /**
     * 音量
     */
    private Integer audiovolume;

    /**
     * 通道类型：1语音输入，0语音输出（原音频传输带宽）
     */
    private Integer bandwidth;

    /**
     * 序号（所在设备序号）
     */
    private Integer num;

    /**
     * 设备编号 
     */
    private String fdCode;

    /**
     * 经度
     */
    private Integer longitude;

    /**
     * 纬度 
     */
    private Integer latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_pohic
     *
     * @mbg.generated Mon Dec 28 10:59:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    public Integer getAudioformat() {
        return audioformat;
    }

    public void setAudioformat(Integer audioformat) {
        this.audioformat = audioformat;
    }

    public Integer getAudiovolume() {
        return audiovolume;
    }

    public void setAudiovolume(Integer audiovolume) {
        this.audiovolume = audiovolume;
    }

    public Integer getBandwidth() {
        return bandwidth;
    }

    public void setBandwidth(Integer bandwidth) {
        this.bandwidth = bandwidth;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public String getFdCode() {
        return fdCode;
    }

    public void setFdCode(String fdCode) {
        this.fdCode = fdCode == null ? null : fdCode.trim();
    }

    public Integer getLongitude() {
        return longitude;
    }

    public void setLongitude(Integer longitude) {
        this.longitude = longitude;
    }

    public Integer getLatitude() {
        return latitude;
    }

    public void setLatitude(Integer latitude) {
        this.latitude = latitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", descs=").append(descs);
        sb.append(", audioformat=").append(audioformat);
        sb.append(", audiovolume=").append(audiovolume);
        sb.append(", bandwidth=").append(bandwidth);
        sb.append(", num=").append(num);
        sb.append(", fdCode=").append(fdCode);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}