package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VResourceChange implements Serializable {
    /**
     * 编号1 
     */
    private Integer id;

    /**
     * 资源编号
     */
    private String code;

    /**
     * 资源类型：1服务资源，2通道资源3设备资源，4告警计划，5录像计划
     */
    private Integer type;

    /**
     * 操作类型，1增加2删除3修改
     */
    private Integer opt;

    /**
     * 创建时间
     */
    private Date createtime;

    /**
     * 该字段在type为通道资源时生效。1视频通道，2告警通道，3语音通道
     */
    private Integer channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_resource_change
     *
     * @mbg.generated Mon Dec 28 10:59:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getOpt() {
        return opt;
    }

    public void setOpt(Integer opt) {
        this.opt = opt;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Integer getChannelType() {
        return channelType;
    }

    public void setChannelType(Integer channelType) {
        this.channelType = channelType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", type=").append(type);
        sb.append(", opt=").append(opt);
        sb.append(", createtime=").append(createtime);
        sb.append(", channelType=").append(channelType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}