package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VResOnlineState implements Serializable {
    /**
     * 资源编号
     */
    private String resCode;

    /**
     * 资源类型：1服务资源，2设备资源，3视频通道，4告警通道，5语音通道
     */
    private Integer type;

    /**
     * 在线状态：0离线，1在线
     */
    private Integer onlineState;

    /**
     * 上线时间
     */
    private Date loginTime;

    /**
     * 下线时间
     */
    private Date logoutTime;

    /**
     * 最后一次心跳时间
     */
    private Date lastHeartBeatTime;

    /**
     * 录像状态：0未录像，1录像中
     */
    private Integer recState;

    /**
     * 录像开始时间
     */
    private Date recStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_res_online_state
     *
     * @mbg.generated Mon Dec 28 10:59:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getResCode() {
        return resCode;
    }

    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getOnlineState() {
        return onlineState;
    }

    public void setOnlineState(Integer onlineState) {
        this.onlineState = onlineState;
    }

    public Date getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public Date getLogoutTime() {
        return logoutTime;
    }

    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    public Date getLastHeartBeatTime() {
        return lastHeartBeatTime;
    }

    public void setLastHeartBeatTime(Date lastHeartBeatTime) {
        this.lastHeartBeatTime = lastHeartBeatTime;
    }

    public Integer getRecState() {
        return recState;
    }

    public void setRecState(Integer recState) {
        this.recState = recState;
    }

    public Date getRecStartTime() {
        return recStartTime;
    }

    public void setRecStartTime(Date recStartTime) {
        this.recStartTime = recStartTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resCode=").append(resCode);
        sb.append(", type=").append(type);
        sb.append(", onlineState=").append(onlineState);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", logoutTime=").append(logoutTime);
        sb.append(", lastHeartBeatTime=").append(lastHeartBeatTime);
        sb.append(", recState=").append(recState);
        sb.append(", recStartTime=").append(recStartTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}