package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VStoragepolies implements Serializable {
    /**
     * 编号
     */
    private Integer id;

    /**
     * 开始时间：格式hh:mi:ss，小时：分：秒
     */
    private Date starttime;

    /**
     * 结束时间：格式hh:mi:ss，小时：分：秒
     */
    private Date endtime;

    /**
     * 码流类型,0主码流，1子码流
     */
    private Integer codetype;

    /**
     * 帧率（fps）
     */
    private Integer framerate;

    /**
     * 创建时间
     */
    private Date createtime;

    /**
     * 修改时间 
     */
    private Date modifytime;

    /**
     * 提前(秒)
     */
    private Integer ahead;

    /**
     * 滞后(秒)
     */
    private Integer lag;

    /**
     * 名称
     */
    private String name;

    /**
     * 周期,//0日 1周 2月3一次性
     */
    private Integer cycle;

    /**
     * 描述
     */
    private String descs;

    /**
     *  '详细信息：如周：1000000代表周计划时只有周一进行录像，1000000000000000000000000000000000表示月计划只有1号进行录像';
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_storagepolies
     *
     * @mbg.generated Mon Dec 28 11:01:48 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getStarttime() {
        return starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    public Date getEndtime() {
        return endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Integer getCodetype() {
        return codetype;
    }

    public void setCodetype(Integer codetype) {
        this.codetype = codetype;
    }

    public Integer getFramerate() {
        return framerate;
    }

    public void setFramerate(Integer framerate) {
        this.framerate = framerate;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public Integer getAhead() {
        return ahead;
    }

    public void setAhead(Integer ahead) {
        this.ahead = ahead;
    }

    public Integer getLag() {
        return lag;
    }

    public void setLag(Integer lag) {
        this.lag = lag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public Integer getCycle() {
        return cycle;
    }

    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", starttime=").append(starttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", codetype=").append(codetype);
        sb.append(", framerate=").append(framerate);
        sb.append(", createtime=").append(createtime);
        sb.append(", modifytime=").append(modifytime);
        sb.append(", ahead=").append(ahead);
        sb.append(", lag=").append(lag);
        sb.append(", name=").append(name);
        sb.append(", cycle=").append(cycle);
        sb.append(", descs=").append(descs);
        sb.append(", detail=").append(detail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}