package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VStorageplans implements Serializable {
    /**
     * 存储计划编号
     */
    private Integer id;

    /**
     * 视频输入通道编号
     */
    private String videoCode;

    /**
     * 是否计划存储1是0否
     */
    private Integer bplanstore;

    /**
     * 周期,//0日 1周 2月3一次性
     */
    private Integer cycle;

    /**
     * 是否事件存储1事件存储0非事件存储
     */
    private Integer beventstore;

    /**
     * 事件存储覆盖周期(按小时)
     */
    private Integer eventConverCycle;

    /**
     * 创建时间
     */
    private Date createtime;

    /**
     * 修改时间 
     */
    private Date modifytime;

    /**
     * 开始时间：格式hh:mi:ss，小时：分：秒
     */
    private Date starttime;

    /**
     * 结束时间：格式hh:mi:ss，小时：分：秒
     */
    private Date endtime;

    /**
     * 码流类型,0主码流，1子码流
     */
    private Integer codetype;

    /**
     * 帧率（fps）
     */
    private Integer framerate;

    /**
     * 提前(秒)
     */
    private Integer ahead;

    /**
     * 滞后(秒)
     */
    private Integer lag;

    /**
     * 名称
     */
    private String name;

    /**
     * 描述
     */
    private String descs;

    /**
     *  '详细信息：如周：1000000代表周计划时只有周一进行录像，1000000000000000000000000000000000表示月计划只有1号进行录像';
     */
    private String detail;

    /**
     * 计划开始时间
     */
    private Date planStarttime;

    /**
     * 计划结束时间
     */
    private Date planEndtime;

    /**
     * 录像覆盖周期(按小时)
     */
    private Integer converCycle;

    /**
     * 录像状态：0未执行，1执行中,2结束
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_storageplans
     *
     * @mbg.generated Mon Dec 28 11:00:39 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVideoCode() {
        return videoCode;
    }

    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode == null ? null : videoCode.trim();
    }

    public Integer getBplanstore() {
        return bplanstore;
    }

    public void setBplanstore(Integer bplanstore) {
        this.bplanstore = bplanstore;
    }

    public Integer getCycle() {
        return cycle;
    }

    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    public Integer getBeventstore() {
        return beventstore;
    }

    public void setBeventstore(Integer beventstore) {
        this.beventstore = beventstore;
    }

    public Integer getEventConverCycle() {
        return eventConverCycle;
    }

    public void setEventConverCycle(Integer eventConverCycle) {
        this.eventConverCycle = eventConverCycle;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public Date getStarttime() {
        return starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    public Date getEndtime() {
        return endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Integer getCodetype() {
        return codetype;
    }

    public void setCodetype(Integer codetype) {
        this.codetype = codetype;
    }

    public Integer getFramerate() {
        return framerate;
    }

    public void setFramerate(Integer framerate) {
        this.framerate = framerate;
    }

    public Integer getAhead() {
        return ahead;
    }

    public void setAhead(Integer ahead) {
        this.ahead = ahead;
    }

    public Integer getLag() {
        return lag;
    }

    public void setLag(Integer lag) {
        this.lag = lag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    public Date getPlanStarttime() {
        return planStarttime;
    }

    public void setPlanStarttime(Date planStarttime) {
        this.planStarttime = planStarttime;
    }

    public Date getPlanEndtime() {
        return planEndtime;
    }

    public void setPlanEndtime(Date planEndtime) {
        this.planEndtime = planEndtime;
    }

    public Integer getConverCycle() {
        return converCycle;
    }

    public void setConverCycle(Integer converCycle) {
        this.converCycle = converCycle;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", videoCode=").append(videoCode);
        sb.append(", bplanstore=").append(bplanstore);
        sb.append(", cycle=").append(cycle);
        sb.append(", beventstore=").append(beventstore);
        sb.append(", eventConverCycle=").append(eventConverCycle);
        sb.append(", createtime=").append(createtime);
        sb.append(", modifytime=").append(modifytime);
        sb.append(", starttime=").append(starttime);
        sb.append(", endtime=").append(endtime);
        sb.append(", codetype=").append(codetype);
        sb.append(", framerate=").append(framerate);
        sb.append(", ahead=").append(ahead);
        sb.append(", lag=").append(lag);
        sb.append(", name=").append(name);
        sb.append(", descs=").append(descs);
        sb.append(", detail=").append(detail);
        sb.append(", planStarttime=").append(planStarttime);
        sb.append(", planEndtime=").append(planEndtime);
        sb.append(", converCycle=").append(converCycle);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}