package com.data.itsv.model;

import java.io.Serializable;

public class VUserloginTimelimit implements Serializable {
    /**
     * 用户编号
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_userlogin_timelimit
     *
     * @mbg.generated Mon Dec 28 11:02:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", code=").append(code);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}