package com.data.itsv.model;

import java.io.Serializable;

public class VVideoAnalysisServerVideo implements Serializable {
    /**
     * 视频分析服务器编号
     */
    private String serverCode;

    /**
     * 摄像机编号
     */
    private String videoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_video_analysis_server_video
     *
     * @mbg.generated Mon Dec 28 11:02:50 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getServerCode() {
        return serverCode;
    }

    public void setServerCode(String serverCode) {
        this.serverCode = serverCode == null ? null : serverCode.trim();
    }

    public String getVideoCode() {
        return videoCode;
    }

    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode == null ? null : videoCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serverCode=").append(serverCode);
        sb.append(", videoCode=").append(videoCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}