package com.data.itsv.model;

import java.io.Serializable;
import java.util.Date;

public class VVideo implements Serializable {
    /**
     * 序号
     */
    private Integer id;

    /**
     * 视频输入通道编号
     */
    private String code;

    /**
     * 摄象机类型
     */
    private Integer cameraTypeCode;

    /**
     * 名称
     */
    private String name;

    /**
     * 安装位置
     */
    private String address;

    /**
     * 经度
     */
    private Integer longitude;

    /**
     * 纬度
     */
    private Integer latitude;

    /**
     * 描述
     */
    private String descs;

    /**
     * 设备编号
     */
    private String fdCode;

    /**
     * 编码格式，h.264
     */
    private Integer codeformat;

    /**
     * 分析类型 ，0 无分析 1 前台分析 2 后台分析
     */
    private Integer analysistype;

    /**
     * 分辨率：0-DCIF(528*384/528*320)，1-CIF(352*288/352*240)，2-QCIF(176*144/176*120)，3-4CIF(704*576/704*480)或D1(720*576/720*486)， 4-2CIF(704*288/704*240)，6-QVGA(320*240)，7-QQVGA(160*120)，12-384*288，13-576*576，16-VGA(640*480)，17-UXGA(1600*1200)， 18-SVGA(800*600)，19-HD720P(1280*720)，20-XVGA(1280*960)，21-HD900P(1600*900)，23-1536*1536，24-1920*1920，27-1920*1080， 28-2560*1920，29-1600*304，30-2048*1536，31-2448*2048，32-2448*1200，33-2448*800，34-XGA(1024*768)，35-SXGA(1280*1024), 36-WD1(960*576/960*480), 37-1080i(1920*1080), 0xff-Auto(使用当前码流分辨率) 
     */
    private Integer realres;

    /**
     * 主码流的标识，0 主码流 
     */
    private Integer realcodetype;

    /**
     * 主图像质量，0 高 1中 2低
     */
    private Integer realimagequality;

    /**
     * 主编码模式 ，0 定码率 1 变码率
     */
    private Integer realcodemodle;

    /**
     * 主码流取流方式，0 tcp 1 rtp
     */
    private Integer realtransmodle;

    /**
     * 子码流图像分辨率
     */
    private Integer recres;

    /**
     * 是否支持子码流0 不支持 1 支持
     */
    private Integer reccodetype;

    /**
     * 子码流图像质量，0 高 1中 2低
     */
    private Integer recimagequality;

    /**
     * 子码流编码模式，0 定码率 1 变码率
     */
    private Integer reccodemodle;

    /**
     * 子码流取流方式 ，0 tcp 1 rtp 2 udp
     */
    private Integer rectransmodle;

    /**
     * 镜头用途
     */
    private String target;

    /**
     * 在所属设备中的视频通道号
     */
    private Integer vchannel;

    /**
     * 在所属设备中的音频通道号
     */
    private Integer achannel;

    /**
     * 是否云台，
     */
    private Integer ptz;

    /**
     * 云台协议 ，/0 PELCO-P 1 PELCO-D 
     */
    private Integer ptzprotocol;

    /**
     * osd名称
     */
    private String osd;

    /**
     * 是否本地镜头，0:非本地镜头(上报上来的镜头) 1:本地镜头
     */
    private Integer blocal;

    /**
     * osd名称是否显示,0:不显示 1 显示 
     */
    private Integer showosd;

    /**
     * osd-x坐标
     */
    private Integer osdx;

    /**
     * osd-y坐标
     */
    private Integer osdy;

    /**
     * 时间是否显示,0:不显示 1 显示 
     */
    private Integer showtime;

    /**
     * 时间-x坐标
     */
    private Integer timex;

    /**
     * 时间-y坐标
     */
    private Integer timey;

    /**
     * 主码流码率256-8192
     */
    private Integer showrealstatus;

    /**
     * 主码流帧率1-60
     */
    private Integer realstatusx;

    /**
     * 主码流I帧间隔1-100
     */
    private Integer realstatusy;

    /**
     * 子码流码率256-8192
     */
    private Integer showrecstatus;

    /**
     * 子码流帧率1-60
     */
    private Integer recstatusx;

    /**
     * 子码流I帧间隔1-100
     */
    private Integer recstatusy;

    /**
     * 智能视频状态显示, 0:不显示 1 显示
     */
    private Integer showanalysisstatus;

    /**
     * 智能状态-x坐标
     */
    private Integer analysisstatusx;

    /**
     * 智能状态-y坐标
     */
    private Integer analysisstatusy;

    /**
     * 创建时间
     */
    private Date createtime;

    /**
     * 修改时间
     */
    private Date modifytime;

    /**
     * 保留字段
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_video
     *
     * @mbg.generated Mon Dec 28 11:02:30 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    public Integer getCameraTypeCode() {
        return cameraTypeCode;
    }

    public void setCameraTypeCode(Integer cameraTypeCode) {
        this.cameraTypeCode = cameraTypeCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public Integer getLongitude() {
        return longitude;
    }

    public void setLongitude(Integer longitude) {
        this.longitude = longitude;
    }

    public Integer getLatitude() {
        return latitude;
    }

    public void setLatitude(Integer latitude) {
        this.latitude = latitude;
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    public String getFdCode() {
        return fdCode;
    }

    public void setFdCode(String fdCode) {
        this.fdCode = fdCode == null ? null : fdCode.trim();
    }

    public Integer getCodeformat() {
        return codeformat;
    }

    public void setCodeformat(Integer codeformat) {
        this.codeformat = codeformat;
    }

    public Integer getAnalysistype() {
        return analysistype;
    }

    public void setAnalysistype(Integer analysistype) {
        this.analysistype = analysistype;
    }

    public Integer getRealres() {
        return realres;
    }

    public void setRealres(Integer realres) {
        this.realres = realres;
    }

    public Integer getRealcodetype() {
        return realcodetype;
    }

    public void setRealcodetype(Integer realcodetype) {
        this.realcodetype = realcodetype;
    }

    public Integer getRealimagequality() {
        return realimagequality;
    }

    public void setRealimagequality(Integer realimagequality) {
        this.realimagequality = realimagequality;
    }

    public Integer getRealcodemodle() {
        return realcodemodle;
    }

    public void setRealcodemodle(Integer realcodemodle) {
        this.realcodemodle = realcodemodle;
    }

    public Integer getRealtransmodle() {
        return realtransmodle;
    }

    public void setRealtransmodle(Integer realtransmodle) {
        this.realtransmodle = realtransmodle;
    }

    public Integer getRecres() {
        return recres;
    }

    public void setRecres(Integer recres) {
        this.recres = recres;
    }

    public Integer getReccodetype() {
        return reccodetype;
    }

    public void setReccodetype(Integer reccodetype) {
        this.reccodetype = reccodetype;
    }

    public Integer getRecimagequality() {
        return recimagequality;
    }

    public void setRecimagequality(Integer recimagequality) {
        this.recimagequality = recimagequality;
    }

    public Integer getReccodemodle() {
        return reccodemodle;
    }

    public void setReccodemodle(Integer reccodemodle) {
        this.reccodemodle = reccodemodle;
    }

    public Integer getRectransmodle() {
        return rectransmodle;
    }

    public void setRectransmodle(Integer rectransmodle) {
        this.rectransmodle = rectransmodle;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    public Integer getVchannel() {
        return vchannel;
    }

    public void setVchannel(Integer vchannel) {
        this.vchannel = vchannel;
    }

    public Integer getAchannel() {
        return achannel;
    }

    public void setAchannel(Integer achannel) {
        this.achannel = achannel;
    }

    public Integer getPtz() {
        return ptz;
    }

    public void setPtz(Integer ptz) {
        this.ptz = ptz;
    }

    public Integer getPtzprotocol() {
        return ptzprotocol;
    }

    public void setPtzprotocol(Integer ptzprotocol) {
        this.ptzprotocol = ptzprotocol;
    }

    public String getOsd() {
        return osd;
    }

    public void setOsd(String osd) {
        this.osd = osd == null ? null : osd.trim();
    }

    public Integer getBlocal() {
        return blocal;
    }

    public void setBlocal(Integer blocal) {
        this.blocal = blocal;
    }

    public Integer getShowosd() {
        return showosd;
    }

    public void setShowosd(Integer showosd) {
        this.showosd = showosd;
    }

    public Integer getOsdx() {
        return osdx;
    }

    public void setOsdx(Integer osdx) {
        this.osdx = osdx;
    }

    public Integer getOsdy() {
        return osdy;
    }

    public void setOsdy(Integer osdy) {
        this.osdy = osdy;
    }

    public Integer getShowtime() {
        return showtime;
    }

    public void setShowtime(Integer showtime) {
        this.showtime = showtime;
    }

    public Integer getTimex() {
        return timex;
    }

    public void setTimex(Integer timex) {
        this.timex = timex;
    }

    public Integer getTimey() {
        return timey;
    }

    public void setTimey(Integer timey) {
        this.timey = timey;
    }

    public Integer getShowrealstatus() {
        return showrealstatus;
    }

    public void setShowrealstatus(Integer showrealstatus) {
        this.showrealstatus = showrealstatus;
    }

    public Integer getRealstatusx() {
        return realstatusx;
    }

    public void setRealstatusx(Integer realstatusx) {
        this.realstatusx = realstatusx;
    }

    public Integer getRealstatusy() {
        return realstatusy;
    }

    public void setRealstatusy(Integer realstatusy) {
        this.realstatusy = realstatusy;
    }

    public Integer getShowrecstatus() {
        return showrecstatus;
    }

    public void setShowrecstatus(Integer showrecstatus) {
        this.showrecstatus = showrecstatus;
    }

    public Integer getRecstatusx() {
        return recstatusx;
    }

    public void setRecstatusx(Integer recstatusx) {
        this.recstatusx = recstatusx;
    }

    public Integer getRecstatusy() {
        return recstatusy;
    }

    public void setRecstatusy(Integer recstatusy) {
        this.recstatusy = recstatusy;
    }

    public Integer getShowanalysisstatus() {
        return showanalysisstatus;
    }

    public void setShowanalysisstatus(Integer showanalysisstatus) {
        this.showanalysisstatus = showanalysisstatus;
    }

    public Integer getAnalysisstatusx() {
        return analysisstatusx;
    }

    public void setAnalysisstatusx(Integer analysisstatusx) {
        this.analysisstatusx = analysisstatusx;
    }

    public Integer getAnalysisstatusy() {
        return analysisstatusy;
    }

    public void setAnalysisstatusy(Integer analysisstatusy) {
        this.analysisstatusy = analysisstatusy;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getReserve() {
        return reserve;
    }

    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", cameraTypeCode=").append(cameraTypeCode);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", descs=").append(descs);
        sb.append(", fdCode=").append(fdCode);
        sb.append(", codeformat=").append(codeformat);
        sb.append(", analysistype=").append(analysistype);
        sb.append(", realres=").append(realres);
        sb.append(", realcodetype=").append(realcodetype);
        sb.append(", realimagequality=").append(realimagequality);
        sb.append(", realcodemodle=").append(realcodemodle);
        sb.append(", realtransmodle=").append(realtransmodle);
        sb.append(", recres=").append(recres);
        sb.append(", reccodetype=").append(reccodetype);
        sb.append(", recimagequality=").append(recimagequality);
        sb.append(", reccodemodle=").append(reccodemodle);
        sb.append(", rectransmodle=").append(rectransmodle);
        sb.append(", target=").append(target);
        sb.append(", vchannel=").append(vchannel);
        sb.append(", achannel=").append(achannel);
        sb.append(", ptz=").append(ptz);
        sb.append(", ptzprotocol=").append(ptzprotocol);
        sb.append(", osd=").append(osd);
        sb.append(", blocal=").append(blocal);
        sb.append(", showosd=").append(showosd);
        sb.append(", osdx=").append(osdx);
        sb.append(", osdy=").append(osdy);
        sb.append(", showtime=").append(showtime);
        sb.append(", timex=").append(timex);
        sb.append(", timey=").append(timey);
        sb.append(", showrealstatus=").append(showrealstatus);
        sb.append(", realstatusx=").append(realstatusx);
        sb.append(", realstatusy=").append(realstatusy);
        sb.append(", showrecstatus=").append(showrecstatus);
        sb.append(", recstatusx=").append(recstatusx);
        sb.append(", recstatusy=").append(recstatusy);
        sb.append(", showanalysisstatus=").append(showanalysisstatus);
        sb.append(", analysisstatusx=").append(analysisstatusx);
        sb.append(", analysisstatusy=").append(analysisstatusy);
        sb.append(", createtime=").append(createtime);
        sb.append(", modifytime=").append(modifytime);
        sb.append(", reserve=").append(reserve);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}