package com.data.itsv.model;

import java.io.Serializable;

public class VVideoStoreState implements Serializable {
    /**
     * 摄像机编号
     */
    private String videoCode;

    /**
     * 摄像机是否有存储计划。0:无，1有
     */
    private Integer existStorePlanFlag;

    /**
     * 摄像机是否有存储计划执行状态。1：未开始、2:开始、3:结束
     */
    private Integer planExeState;

    /**
     * 摄像机存储状态。1：正常、2:断流
     */
    private Integer storeState;

    /**
     * 存储状态异常断流描述。
     */
    private String storeExceptionDesc;

    /**
     * 存储计划类型.1:前端存储，2中心存储
     */
    private Integer storePlanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_video_store_state
     *
     * @mbg.generated Mon Dec 28 11:03:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getVideoCode() {
        return videoCode;
    }

    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode == null ? null : videoCode.trim();
    }

    public Integer getExistStorePlanFlag() {
        return existStorePlanFlag;
    }

    public void setExistStorePlanFlag(Integer existStorePlanFlag) {
        this.existStorePlanFlag = existStorePlanFlag;
    }

    public Integer getPlanExeState() {
        return planExeState;
    }

    public void setPlanExeState(Integer planExeState) {
        this.planExeState = planExeState;
    }

    public Integer getStoreState() {
        return storeState;
    }

    public void setStoreState(Integer storeState) {
        this.storeState = storeState;
    }

    public String getStoreExceptionDesc() {
        return storeExceptionDesc;
    }

    public void setStoreExceptionDesc(String storeExceptionDesc) {
        this.storeExceptionDesc = storeExceptionDesc == null ? null : storeExceptionDesc.trim();
    }

    public Integer getStorePlanType() {
        return storePlanType;
    }

    public void setStorePlanType(Integer storePlanType) {
        this.storePlanType = storePlanType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoCode=").append(videoCode);
        sb.append(", existStorePlanFlag=").append(existStorePlanFlag);
        sb.append(", planExeState=").append(planExeState);
        sb.append(", storeState=").append(storeState);
        sb.append(", storeExceptionDesc=").append(storeExceptionDesc);
        sb.append(", storePlanType=").append(storePlanType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}