package com.data.itsv.model;

import java.io.Serializable;

public class VVssVideo implements Serializable {
    /**
     * 存储服务编号
     */
    private String vssCode;

    /**
     * 视频输入通道编号
     */
    private String videoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_vss_video
     *
     * @mbg.generated Mon Dec 28 11:03:31 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getVssCode() {
        return vssCode;
    }

    public void setVssCode(String vssCode) {
        this.vssCode = vssCode == null ? null : vssCode.trim();
    }

    public String getVideoCode() {
        return videoCode;
    }

    public void setVideoCode(String videoCode) {
        this.videoCode = videoCode == null ? null : videoCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vssCode=").append(vssCode);
        sb.append(", videoCode=").append(videoCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}