package com.data.itsv.model;

import java.io.Serializable;

public class VWatchPointVideoin implements Serializable {
    /**
     * 监控点编号
     */
    private Integer watchPointId;

    /**
     * 设备类型编号
     */
    private String videoinCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_watch_point_videoin
     *
     * @mbg.generated Mon Dec 28 11:33:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getWatchPointId() {
        return watchPointId;
    }

    public void setWatchPointId(Integer watchPointId) {
        this.watchPointId = watchPointId;
    }

    public String getVideoinCode() {
        return videoinCode;
    }

    public void setVideoinCode(String videoinCode) {
        this.videoinCode = videoinCode == null ? null : videoinCode.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", watchPointId=").append(watchPointId);
        sb.append(", videoinCode=").append(videoinCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}