server:
  port: 8888


spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://172.16.149.239:3306/chuanzang?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  #MQ配置IP 端口
  rabbitmq:
    host: 47.92.100.23
    port: 5673
    username: admin
    password: 1qaz!QAZ
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
  redis:
    # 数据库索引，默认0
    database: 0
    #    # 服务器IP地址
    host: 172.16.149.220
    #    # 连接端口
    port: 6379
    #    # Redis服务器连接密码（默认为空）
    #    password:

    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 800
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 2
    # 连接超时时间（毫秒）
    timeout: 30000
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.data.itsv.model

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0


#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mapper4 配置
mapper:
  mappers: com.data.itsv.base.BaseMapper
  not-empty: false
  identity: MYSQL

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR


bootshiro:
  enableEncryptPassword: true


cms:
  ip: "127.0.0.1"
  port: "9001"


netty:
  client:
    #host: "39.103.130.69"
    host: "172.23.37.86"
    port: "9001"
  server:
    port: "30002"


heartbeatTime: "120"

setVideoCode: "01010207013005000135"
userName: "admin"
password: "admin"
jwt:
  timeOut: 10000 #超时时间
  intervalTime: 1800 #在和超时时间相差1800秒之内 重新下发jwt token
